docker_name_prefix: golangpgmcp
instance_count: 1
starting_port: 9777
databases_per_instance: 10
tmpfs_size: 1024m
shm_size: 1g
locker_port: 9776
auto_unlock_minutes: 5
pg_username: tester
password: pgflock
database_prefix: tester
extensions: []
postgres_version: "15"
encoding: UTF8
lc_collate: en_US.UTF-8
lc_ctype: en_US.UTF-8
max_connections: 5000
